In [1]:
import pandas as pd
from google.cloud import storage

BUCKET = "filipburger-flight-data-lake"
PREFIX = "raw/bts_lookups"


def load_lookups(bucket: str = BUCKET, prefix: str = PREFIX) -> dict[str, pd.DataFrame]:
    """Load every lookup parquet from GCS into a dict keyed by table name."""
    client = storage.Client()
    frames = {}
    for blob in client.list_blobs(bucket, prefix=prefix):
        if not blob.name.endswith(".parquet"):
            continue
        table = blob.name.split("/")[-2]        # raw/bts_lookups/<table>/data.parquet
        frames[table] = pd.read_parquet(f"gs://{bucket}/{blob.name}")
    return frames


lookups = load_lookups()
print(f"Loaded {len(lookups)} tables")

Loaded 16 tables

In [20]:
summary = pd.DataFrame([
    {
        "table": name,
        "rows": len(df),
        "cols": len(df.columns),
        "columns": ", ".join(c for c in df.columns if not c.startswith("_")),
    }
    for name, df in sorted(lookups.items())
])
summary

                    table  rows  cols            columns
0            l_airline_id  1778     3  Code, Description
1          l_cancellation     4     3  Code, Description
2       l_carrier_history  2075     3  Code, Description
3        l_city_market_id  6181     3  Code, Description
4             l_deparrblk    19     3  Code, Description
5    l_distance_group_250    11     3  Code, Description
6            l_diversions     7     3  Code, Description
7                l_months    12     3  Code, Description
8   l_ontime_delay_groups    15     3  Code, Description
9              l_quarters     4     3  Code, Description
10   l_state_abr_aviation    67     3  Code, Description
11           l_state_fips    74     3  Code, Description
12      l_unique_carriers  1778     3  Code, Description
13             l_weekdays     8     3  Code, Description
14     l_world_area_codes   333     3  Code, Description
15           l_yesno_resp     2     3  Code, Description

In [21]:
for name, df in sorted(lookups.items()):
    print(f"\n{'─' * 70}\n{name}  ({len(df):,} rows)")
    print(df.drop(columns=[c for c in df.columns if c.startswith("_")]).head(3).to_string(index=False))

──────────────────────────────────────────────────────────────────────
l_airline_id  (1,778 rows)
 Code                     Description
19031  Mackey International Inc.: MAC
19032 Munz Northern Airlines Inc.: XY
19033      Cochise Airlines Inc.: COC

──────────────────────────────────────────────────────────────────────
l_cancellation  (4 rows)
Code         Description
   A             Carrier
   B             Weather
   C National Air System

──────────────────────────────────────────────────────────────────────
l_carrier_history  (2,075 rows)
Code                       Description
 02Q           Titan Airways (2006 - )
 04Q  Tradewind Aviation (2006 - 2023)
 05Q Comlux Aviation, AG (2006 - 2012)

──────────────────────────────────────────────────────────────────────
l_city_market_id  (6,181 rows)
 Code          Description
30001     Afognak Lake, AK
30003 Granite Mountain, AK
30004              Lik, AK

──────────────────────────────────────────────────────────────────────
l_deparrblk  (19 rows)
     Code       Description
0001-0559 12:00AM to 5:59AM
0600-0659  6:00AM to 6:59AM
0700-0759  7:00AM to 7:59AM

──────────────────────────────────────────────────────────────────────
l_distance_group_250  (11 rows)
Code         Description
   1 Less Than 250 Miles
   2       250-499 Miles
   3       500-749 Miles

──────────────────────────────────────────────────────────────────────
l_diversions  (7 rows)
Code                   Description
   0        Flight is not Diverted
   1  One Diverted Airport Landing
   2 Two Diverted Airport Landings

──────────────────────────────────────────────────────────────────────
l_months  (12 rows)
Code Description
   1     January
   2    February
   3       March

──────────────────────────────────────────────────────────────────────
l_ontime_delay_groups  (15 rows)
Code                      Description
  -2              Delay < -15 minutes
  -1 Delay between -15 and -1 minutes
   0   Delay between 0 and 14 minutes

──────────────────────────────────────────────────────────────────────
l_quarters  (4 rows)
Code                  Description
   1  Quarter1:January 1-March 31
   2     Quarter2:April 1-June 30
   3 Quarter3:July 1-September 30

──────────────────────────────────────────────────────────────────────
l_state_abr_aviation  (67 rows)
Code     Description
  AB Alberta, Canada
  AK          Alaska
  AL         Alabama

──────────────────────────────────────────────────────────────────────
l_state_fips  (74 rows)
Code    Description
  00 Not Applicable
  01        Alabama
  02         Alaska

──────────────────────────────────────────────────────────────────────
l_unique_carriers  (1,778 rows)
Code                   Description
 02Q                 Titan Airways
 05Q           Comlux Aviation, AG
 06Q Master Top Linhas Aereas Ltd.

──────────────────────────────────────────────────────────────────────
l_weekdays  (8 rows)
Code Description
   1      Monday
   2     Tuesday
   3   Wednesday

──────────────────────────────────────────────────────────────────────
l_world_area_codes  (333 rows)
Code Description
   1      Alaska
   2      Hawaii
   3 Puerto Rico

──────────────────────────────────────────────────────────────────────
l_yesno_resp  (2 rows)
Code Description
   0          No
   1         Yes

We ned only:
- l_unique_carriers table join IATA_CODE_Reporting_Airline on .Code, to get carrier name
hidden in .Description

- l_cancellation table to join on CancellationCode to get cancellation cause in Description

- l_ontime_delay_groups to join DepartureDelayGroups, ArrivalDelayGroups

In [28]:
iatas =["9E",
"AA",
"AS",
"B6",
"DL",
"F9",
"G4",
"HA",
"MQ",
"NK",
"OH",
"OO",
"UA",
"WN",
"YX"]

In [21]:
ids = ["20363",
"19805",
"19930",
"20409",
"19790",
"20436",
"20368",
"19690",
"20398",
"20416",
"20397",
"20304",
"19977",
"19393",
"20452"]

In [23]:
airline_id = lookups['l_airline_id']
airline_id_filtered = airline_id[(airline_id['Code'].isin(ids))]

In [24]:
airline_id_filtered

       Code                 Description                     _ingested_at
362   19393  Southwest Airlines Co.: WN 2026-08-16 09:35:14.815304+00:00
659   19690  Hawaiian Airlines Inc.: HA 2026-08-16 09:35:14.815304+00:00
758   19790    Delta Air Lines Inc.: DL 2026-08-16 09:35:14.815304+00:00
773   19805  American Airlines Inc.: AA 2026-08-16 09:35:14.815304+00:00
898   19930    Alaska Airlines Inc.: AS 2026-08-16 09:35:14.815304+00:00
945   19977   United Air Lines Inc.: UA 2026-08-16 09:35:14.815304+00:00
1271  20304   SkyWest Airlines Inc.: OO 2026-08-16 09:35:14.815304+00:00
1330  20363       Endeavor Air Inc.: 9E 2026-08-16 09:35:14.815304+00:00
1335  20368           Allegiant Air: G4 2026-08-16 09:35:14.815304+00:00
1363  20397       PSA Airlines Inc.: OH 2026-08-16 09:35:14.815304+00:00
1364  20398               Envoy Air: MQ 2026-08-16 09:35:14.815304+00:00
1375  20409         JetBlue Airways: B6 2026-08-16 09:35:14.815304+00:00
1382  20416        Spirit Air Lines: NK 2026-08-16 09:35:14.815304+00:00
1402  20436  Frontier Airlines Inc.: F9 2026-08-16 09:35:14.815304+00:00
1418  20452        Republic Airline: YX 2026-08-16 09:35:14.815304+00:00

In [10]:
airline_id.info()

<class 'pandas.DataFrame'>
RangeIndex: 1778 entries, 0 to 1777
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Code          1778 non-null   string
 1   Description   1778 non-null   string
 2   _ingested_at  1778 non-null   datetime64[us, UTC]
dtypes: datetime64[us, UTC](1), string(2)
memory usage: 94.8 KB

In [24]:

airline_id[airline_id['Code']== '19393']

      Code                 Description                     _ingested_at
362  19393  Southwest Airlines Co.: WN 2026-08-16 09:35:14.815304+00:00

In [25]:
carriers = lookups['l_unique_carriers']

In [26]:
carriers[carriers['Code']=='WN']

     Code             Description                     _ingested_at
1652   WN  Southwest Airlines Co. 2026-08-16 09:35:14.595406+00:00

In [26]:
carrier_history = lookups['l_carrier_history']
carrier_history.head(30)

,Code,Description,_ingested_at
0,02Q,Titan Airways (2006 - ),2026-08-16 09:35:14.925882+00:00
1,04Q,Tradewind Aviation (2006 - 2023),2026-08-16 09:35:14.925882+00:00
2,05Q,"Comlux Aviation, AG (2006 - 2012)",2026-08-16 09:35:14.925882+00:00
3,06Q,Master Top Linhas Aereas Ltd. (2007 - ),2026-08-16 09:35:14.925882+00:00
4,07Q,Flair Airlines Ltd. (2007 - ),2026-08-16 09:35:14.925882+00:00
5,09Q,"Swift Air, LLC (2006 - 2017)",2026-08-16 09:35:14.925882+00:00
6,09Q,"Swift Air, LLC d/b/a Eastern Air Lines d/b/a E...",2026-08-16 09:35:14.925882+00:00
7,0BQ,DCA (2007 - ),2026-08-16 09:35:14.925882+00:00
8,0CQ,ACM AIR CHARTER GmbH (2007 - ),2026-08-16 09:35:14.925882+00:00
9,0FQ,"Maine Aviation Aircraft Charter, LLC (2017 - )",2026-08-16 09:35:14.925882+00:00
10,0GQ,"Inter Island Airways, d/b/a Inter Island Air (...",2026-08-16 09:35:14.925882+00:00
11,0HQ,Polar Airlines de Mexico d/b/a Nova Air (2007 - ),2026-08-16 09:35:14.925882+00:00
12,0IQ,Lynx Aviation d/b/a Frontier Airlines (2007 - ...,2026-08-16 09:35:14.925882+00:00
13,0J,JetClub AG (2007 - ),2026-08-16 09:35:14.925882+00:00
14,0JQ,Vision Airlines (2008 - 2015),2026-08-16 09:35:14.925882+00:00
15,0KQ,"Mokulele Flight Services, Inc. (2006 - 2012)",2026-08-16 09:35:14.925882+00:00
16,0LQ,"Metropix UK, LLP. (2007 - )",2026-08-16 09:35:14.925882+00:00
17,0MQ,"Multi-Aero, Inc. d/b/a Air Choice One (2008 - ...",2026-08-16 09:35:14.925882+00:00
18,0OQ,Open Skies (2008 - 2009),2026-08-16 09:35:14.925882+00:00
19,0Q,Flying Service N.V. (2007 - ),2026-08-16 09:35:14.925882+00:00
20,0QQ,TAG Aviation (UK) Ltd. (2006 - ),2026-08-16 09:35:14.925882+00:00
21,0RQ,TAG Aviation Espana S.L. (2006 - ),2026-08-16 09:35:14.925882+00:00
22,0TQ,"Corporatejets, XXI (2008 - 2013)",2026-08-16 09:35:14.925882+00:00
23,0UQ,"Comlux Malta, Ltd. (2009 - )",2026-08-16 09:35:14.925882+00:00
24,0VQ,Ocean Sky (UK) Limited (2009 - ),2026-08-16 09:35:14.925882+00:00
25,0WQ,Avjet Corporation (2009 - 2021),2026-08-16 09:35:14.925882+00:00
26,0YQ,Comlux Malta Ltd. (2009 - ),2026-08-16 09:35:14.925882+00:00
27,0Z,Island Air Service (2005 - 2007),2026-08-16 09:35:14.925882+00:00
28,0ZQ,Air Excursions LLC (2009 - 2009),2026-08-16 09:35:14.925882+00:00
29,10Q,Swiss Air Ambulance (2010 - ),2026-08-16 09:35:14.925882+00:00

In [30]:
filtered_carrier_history = carrier_history[carrier_history['Code'].isin(iatas)]

In [31]:
filtered_carrier_history

,Code,Description,_ingested_at
208,9E,Endeavor Air Inc. (2013 - ),2026-08-16 09:35:14.925882+00:00
209,9E,Pinnacle Airlines Inc. (2002 - 2013),2026-08-16 09:35:14.925882+00:00
231,AA,American Airlines Inc. (1960 - ),2026-08-16 09:35:14.925882+00:00
375,AS,Alaska Airlines Inc. (1960 - ),2026-08-16 09:35:14.925882+00:00
425,B6,JetBlue Airways (2000 - ),2026-08-16 09:35:14.925882+00:00
650,DL,Delta Air Lines Inc. (1960 - ),2026-08-16 09:35:14.925882+00:00
753,F9,Frontier Airlines Inc. (1994 - ),2026-08-16 09:35:14.925882+00:00
807,G4,Allegiant Air (2000 - ),2026-08-16 09:35:14.925882+00:00
885,HA,Hawaiian Airlines Inc. (1960 - 2025),2026-08-16 09:35:14.925882+00:00
1211,MQ,Simmons Airlines (1991 - 1998),2026-08-16 09:35:14.925882+00:00
1212,MQ,Envoy Air (2014 - ),2026-08-16 09:35:14.925882+00:00
1213,MQ,American Eagle Airlines Inc. (1998 - 2014),2026-08-16 09:35:14.925882+00:00
1283,NK,Spirit Air Lines (1992 - ),2026-08-16 09:35:14.925882+00:00
1325,OH,Comair Inc. (2000 - 2012),2026-08-16 09:35:14.925882+00:00
1326,OH,PSA Airlines Inc. (2015 - ),2026-08-16 09:35:14.925882+00:00
1342,OO,SkyWest Airlines Inc. (2003 - ),2026-08-16 09:35:14.925882+00:00
1792,UA,United Air Lines Inc. (1960 - ),2026-08-16 09:35:14.925882+00:00
1917,WN,Southwest Airlines Co. (1979 - ),2026-08-16 09:35:14.925882+00:00
2038,YX,Republic Airline (2017 - ),2026-08-16 09:35:14.925882+00:00
2039,YX,"Midwest Airline, Inc. (2003 - 2009)",2026-08-16 09:35:14.925882+00:00
2040,YX,Midwest Express Airlines (1984 - 2003),2026-08-16 09:35:14.925882+00:00
2041,YX,Republic Airlines (2009 - 2016),2026-08-16 09:35:14.925882+00:00